name: PlantUML Diagrams

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Generate PlantUML Diagrams
      run: |
        java -jar /diagramme_uml/uml.jar -tsvg README.md
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update PlantUML diagrams in README" || exit 0
        git push