@startuml

skinparam class {
    BackgroundColor LightGoldenRodYellow
    BorderColor black
}

class "Site Web" {
    # nom: str
    - url_recherche : list<str>
    - WebScrapping(nom_article: str): list<Article>
}

class "Interface Utilisateur" {
    + requete
    - AfficherCarte()
    - AfficherHistogramme()
    - AfficherGraphique()
}

class Article {
    # nom: str
    # prix: float
    # id_article: str
    # pays : str
}

class Produit {
    # nom: str
    # articles: dict{str, article}
    # CalculIndicesProduit() : float
    + AjouteDonneesExterieures(Dict[str, Article]) 
}

class "Catégorie Produit" {
    # nom: str
    # produits: dict[str, Produit]
    # CalculIndicesCategorie() : float
}

class Pays {
    + nom : str
    + devise : str
    + IndcicesProduits : dict[str, float]
    + IndcicesCategorieProduit : dict[str, float]
    # ConversionEuros() : float
    - ObtientTauxChange(devise: str) : float
}

"Site Web" --* Article
Article --* Produit
Produit --* "Catégorie Produit"

Pays -- "Interface Utilisateur"
Pays-- "Catégorie Produit"
Pays -- Produit
@enduml
